//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiGaraOto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int ID { get; set; }
        public Nullable<int> ReceptionID { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<decimal> Proceeds { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Reception Reception { get; set; }
    }
}
