//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiGaraOto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryReportDetail
    {
        public int InventoryReportID { get; set; }
        public int SuppliesID { get; set; }
        public Nullable<int> TonDau { get; set; }
        public Nullable<int> PhatSinh { get; set; }
        public Nullable<int> TonCuoi { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual InventoryReport InventoryReport { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
