//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiGaraOto.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLiGaraOtoEntities : DbContext
    {
        public QuanLiGaraOtoEntities()
            : base("name=QuanLiGaraOtoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<BrandCar> BrandCars { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<InventoryReport> InventoryReports { get; set; }
        public virtual DbSet<InventoryReportDetail> InventoryReportDetails { get; set; }
        public virtual DbSet<Parameter> Parameters { get; set; }
        public virtual DbSet<Reception> Receptions { get; set; }
        public virtual DbSet<Repair> Repairs { get; set; }
        public virtual DbSet<RepairDetail> RepairDetails { get; set; }
        public virtual DbSet<RepairSuppliesDetail> RepairSuppliesDetails { get; set; }
        public virtual DbSet<Revenue> Revenues { get; set; }
        public virtual DbSet<RevenueDetail> RevenueDetails { get; set; }
        public virtual DbSet<Supply> Supplies { get; set; }
        public virtual DbSet<SuppliesInput> SuppliesInputs { get; set; }
        public virtual DbSet<SuppliesInputDetail> SuppliesInputDetails { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Wage> Wages { get; set; }
    }
}
