//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiGaraOto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevenueDetail
    {
        public int RevenueId { get; set; }
        public int BrandCarId { get; set; }
        public Nullable<int> RepairCount { get; set; }
        public Nullable<double> Ratio { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual BrandCar BrandCar { get; set; }
        public virtual Revenue Revenue { get; set; }
    }
}
