//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiGaraOto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supply()
        {
            this.InventoryReportDetails = new HashSet<InventoryReportDetail>();
            this.RepairSuppliesDetails = new HashSet<RepairSuppliesDetail>();
            this.SuppliesInputDetails = new HashSet<SuppliesInputDetail>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> CountInStock { get; set; }
        public Nullable<decimal> InputPrices { get; set; }
        public Nullable<decimal> OutputPrices { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryReportDetail> InventoryReportDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepairSuppliesDetail> RepairSuppliesDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuppliesInputDetail> SuppliesInputDetails { get; set; }
    }
}
